In [5]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC 
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import  RandomForestClassifier
import matplotlib.pyplot as plt
%matplotlib inline


In [6]:
from sklearn.datasets import load_digits
digits = load_digits()

In [7]:
from sklearn.model_selection import train_test_split
x_train ,x_test ,y_train ,y_test = train_test_split(digits.data,digits.target ,test_size=0.3)

# using logistic regression model 

In [9]:
lreg = LogisticRegression()
lreg.fit(x_train ,y_train)
lreg.score(x_test ,y_test) * 100

/Users/apple/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


97.03703703703704

# using svm model 

In [10]:
lreg = SVC()
lreg.fit(x_train ,y_train)
lreg.score(x_test ,y_test) * 100

98.88888888888889

# random forest classifier model

In [11]:
lreg = RandomForestClassifier()
lreg.fit(x_train ,y_train)
lreg.score(x_test ,y_test) * 100

98.14814814814815

# importing kfold

In [12]:
from sklearn.model_selection import KFold

# spliting k fold into 3

In [14]:
kf = KFold(n_splits=3)

In [15]:
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [16]:
for train_index ,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index ,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


# using function to calculte the score accuracy 

In [17]:
def get_score(model ,x_train,x_test,y_train ,y_test):
    model.fit(x_train ,y_train)
    return model.score(x_test ,y_test)

# logistic regression model

In [20]:
get_score(LogisticRegression(),x_train,x_test,y_train ,y_test) *100

/Users/apple/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


97.03703703703704

# svm model using function

In [21]:
get_score(SVC(),x_train,x_test,y_train ,y_test) *100

98.88888888888889

# Random forest model in function

In [22]:
get_score(RandomForestClassifier(),x_train,x_test,y_train ,y_test) *100

97.5925925925926

# using stratified kfold model 

In [91]:
from sklearn.model_selection import StratifiedKFold 
stk =StratifiedKFold(n_splits=3)

In [92]:
score_logistic =[]
score_svm = []
score_random =[]

for train_index ,test_index in kf.split(digits.data):
    x_train ,x_test ,y_train,y_test = digits.data[train_index],digits.data[test_index] , \
                                      digits.target[train_index],digits.target[test_index]
    
    score_logistic.append(get_score(LogisticRegression(),x_train,x_test,y_train ,y_test))
    score_svm.append(get_score(SVC(),x_train,x_test,y_train ,y_test)) 
    score_random.append(get_score(RandomForestClassifier(n_estimators=40),x_train,x_test,y_train ,y_test))

/Users/apple/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/apple/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logis

# stratifiedkfold score accuracy

In [93]:
score_logistic 

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [94]:
score_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [95]:
score_random

[0.9315525876460768, 0.9432387312186978, 0.9131886477462438]

# using cross validation to perform same operations

In [96]:
from sklearn.model_selection import cross_val_score

# performing logistic regression using cross validation

In [97]:
cross_val_score(LogisticRegression() ,digits.data ,digits.target) 

/Users/apple/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/apple/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logis

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [98]:
cross_val_score(LogisticRegression() ,digits.data ,digits.target) *100

/Users/apple/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/apple/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logis

array([92.22222222, 86.94444444, 94.15041783, 93.8718663 , 89.69359331])

# performing svm oerations using cross validation 

In [103]:
cross_val_score(SVC() ,digits.data ,digits.target) 

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [104]:
cross_val_score(SVC() ,digits.data ,digits.target) *100

array([96.11111111, 94.44444444, 98.32869081, 98.88579387, 93.8718663 ])

# performing random forest operation using cross validation

In [105]:
cross_val_score(RandomForestClassifier() ,digits.data ,digits.target) 

array([0.93611111, 0.91111111, 0.95821727, 0.97493036, 0.93314763])

# parameter tuning

In [106]:
cross_val_score(RandomForestClassifier() ,digits.data ,digits.target) * 100

array([92.5       , 90.27777778, 96.37883008, 96.10027855, 92.2005571 ])

In [109]:
cross_val_score(RandomForestClassifier(n_estimators=40) ,digits.data ,digits.target) 

array([0.91111111, 0.90833333, 0.95821727, 0.97493036, 0.91643454])

In [108]:
cross_val_score(RandomForestClassifier(n_estimators=5) ,digits.data ,digits.target) 

array([0.84166667, 0.83055556, 0.88857939, 0.91086351, 0.86072423])

In [110]:
cross_val_score(RandomForestClassifier(n_estimators=20) ,digits.data ,digits.target) 

array([0.92777778, 0.88055556, 0.94150418, 0.95543175, 0.89415042])